from sqlalchemy import select
from app.core.database import SessionLocal
from app.modules.survey.models import Question

QUESTIONS = [
    (1,  "FOI DEUS QUEM CRIOU A PENA DE MORTE? GENESIS 9:5,6"),
    (2,  "EXISTE JUSTIÇA PARA ASSASSINOS NO BRASIL?\nJUSTIÇA É A IGUALDADE DE DIREITO ONDE A PENA É IGUAL AO DELITO, E CASO HAJA DESIGUALDADE ENTRE AMBOS HOUVE INJUSTIÇA."),
    (3,  "UM BANDIDO MATA TODA UMA FAMÍLIA E GANHA 30 ANOS DE PRISÃO E SAI CUMPRIDO 1/3 DA PENA (DEZ ANOS). HOUVE JUSTIÇA?\nAQUELAS VIDAS SÓ VALEM DEZ ANOS DE PRISÃO DA VIDA DO ASSASSINO? O DIREITO DO ASSASSINO É MAIOR QUE O DO MORTO? UM É CIDADÃO DE 1ª E O OUTRO DE 2ª?\nART. 5º DA CONSTITUIÇÃO: Todos são iguais perante a lei, sem distinção de qualquer natureza...,etc."),
    (4,  "VOCÊ É A FAVOR DA “PENA DE MORTE” PARA FEMINICIDA, ASSASSINO DE MULHER (ESPOSA, NAMORADA, ETC)?\nE QUE OS SEUS BENS SEJAM ESPOLIADOS PARA RESSARCIR AOS FAMILIARES DA VÍTIMA.\nCERCA DE 10 MULHERES SÃO ASSASSINADAS TODOS OS DIAS NO BRASIL.\n“A LEI MARIA DA PENHA” SÓ DIMINUIU EM 10% O FEMINICÍDIO NO BRASIL."),
    (5,  "TALVEZ VOCÊ NÃO SEJA A FAVOR DA “PENA DE MORTE”, MAS VOCÊ CONCORDA COM A “LEI GANDHI ANTI-FEMINICÍDIO” DE PROTEÇÃO À VIDA E À INTEGRIDADE FÍSICA DA MULHER (“LEI DA IGUALITARIEDADE DE DIREITOS”, “LEI DA JUSTA RECOMPENSA”):\nSE ALGUÉM AGRIDE-A, FERINDO-A, MUTILANDO-A, INCENDIANDO-A, CAUSANDO-LHE MALES E DEFORMAÇÕES FÍSICAS, SEJA-LHE FEITO O MESMO, NA MESMA PROPORÇÃO, MAIS A PENA DE PRISÃO PREVISTA NA LEI E A ESPOLIAÇÃO DOS SEUS BENS PARA INDENIZAÇÃO À REFERIDA MULHER?\nCERCA DE 21 MILHÕES DE MULHERES FORAM AGREDIDAS E ESPANCADAS EM 2017."),
    (6,  "VOCÊ É A FAVOR DA “PENA DE MORTE” PARA ASSASSINO MAIOR DE 18 ANOS, E QUE OS SEUS BENS SEJAM ESPOLIADOS PARA INDENIZAR A FAMÍLIA DA VÍTIMA?\nMAIS DE 40 MIL PESSOAS SÃO ASSASSINADAS TODOS OS ANOS NO BRASIL."),
    (7,  "VOCÊ É A FAVOR DA “PENA DE MORTE” PARA RAPTORES (SEQUESTRADORES) DE PESSOAS PARA TRABALHO SEXUAL OU TRABALHO ESCRAVO?\nSEGUNDO A ONU CERCA DE 2,5 MILHÕES DE PESSOAS POR ANO EM TODO O MUNDO SÃO VÍTIMAS DE TRÁFICO INTERNACIONAL (96,36% SÃO MULHERES, METADE SÃO CRIANÇAS), MOVIMENTANDO 150 BILHÕES DE DÓLARES POR ANO.\nE QUE OS SEUS BENS SEJAM ESPOLIADOS PARA RESSARCIR AOS FAMILIARES DA VÍTIMA?"),
    (8,  "VOCÊ É A FAVOR DA “PENA DE MORTE” DE POLÍTICO OU FUNCIONÁRIO PÚBLICO CIVIL OU MILITAR QUE DESVIA DINHEIRO PÚBLICO (PECULATO)?\nCRIME CONTRA O POVO (GENOCÍDIO); E QUE OS SEUS BENS SEJAM ESPOLIADOS PARA RESSARCIR O ESTADO BRASILEIRO?\nCERCA DE 153 MIL MORTES POR ANO SÃO CAUSADAS POR MAL ATENDIMENTO OU FALTA DE MÉDICOS NO SUS POR CAUSA DO DESVIO DE VERBA DO ESTADO."),
    (9,  "VOCÊ CONCORDA QUE O BANDIDO QUE DÁ UM TIRO NA CABEÇA DE UMA PESSOA INDEFESA É MAIS IMPIEDOSO DO QUE O POLÍTICO QUE DESVIA 100 MILHÕES DOS COFRES PÚBLICOS?\nO BANDIDO MATA APENAS UM, O POLÍTICO MATA MILHÕES ANUALMENTE, IMPEDINDO QUE O ESTADO AJUDE OS POBRES E NECESSITADOS: CERCA DE 300 BILHÕES DE REAIS SÃO DESVIADOS TODOS OS ANOS."),
    (10, "VOCÊ É A FAVOR DA “LEI GANDHI ANTI-AUMENTO SALARIAL DOS POLÍTICOS” QUE PROÍBE AOS PARLAMENTARES DE VOTAREM EM PROJETOS DE LEI QUE VISEM AUMENTAR SEUS PRÓPRIOS SALÁRIOS?\nE QUE ISSO SEJA FEITO POR COMISSÕES INDEPENDENTES E SANCIONADA PELO PRESIDENTE DA REPÚBLICA OU PELO STF, DE ACORDO COM O PERCENTUAL DA INFLAÇÃO, COMO QUALQUER TRABALHADOR BRASILEIRO?"),
    (11, "VOCÊ É A FAVOR DA “LEI GANDHI DE PROTEÇÃO À VÍTIMA DE RAPTO”, QUE OBRIGA O RAPTOR, SOB PENA DE CHICOTADAS, A CONFESSAR ONDE ESCONDEU A VÍTIMA RAPTADA POUCAS HORAS ANTES DA PRISÃO (SÓ EM CASO DE RAPTO RECENTE E IMEDIATO, HAVENDO POSSIBILIDADES DE A VÍTIMA AINDA ESTAR VIVA)?\nO ARTIGO 5º, INCISO III DA CONSTITUIÇÃO: “NINGUÉM SERÁ SUBMETIDO A TORTURA NEM A TRATAMENTO DESUMANO OU DEGRADANTE”."),
    (12, "VOCÊ CONCORDA COM A “LEI GANDHI DE PROTEÇÃO À SAÚDE, À EDUCAÇÃO E À PESQUISA”, QUE PROPÕE QUE A VERBA DESTINADA ÀS MESMAS SEJA SEMPRE AUMENTADA NO MÍNIMO IGUAL OU ACIMA DA INFLAÇÃO E JAMAIS POSSA SER DIMINUÍDA?\nE QUE SEJA FEITA UMA EMENDA CONSTITUCIONAL TRANSFORMANDO A REFERIDA LEI EM “CLÁUSULA PÉTREA” (IMUTÁVEL)?"),
    (13, "VOCÊ É A FAVOR DA “PENA DE MORTE” PARA ASSASSINO MENOR DE 18 ANOS, MAS ACIMA DE 12 ANOS?\nA LEI DA INIMPUTABILIDADE PARA MENORES DE 18 ANOS É INCONSTITUCIONAL (segundo o texto fornecido)."),
    (14, "VOCÊ É A FAVOR DA “PENA DE MORTE” PARA POLICIAL ASSASSINO DE PESSOA DESARMADA E INDEFESA, E QUE OS SEUS BENS SEJAM ESPOLIADOS PARA RESSARCIR AOS FAMILIARES DA VÍTIMA?"),
    (15, "VOCÊ É A FAVOR DA “PENA DE MORTE” PARA POLICIAL CÚMPLICE E FALSA TESTEMUNHA EM FAVOR DE POLICIAL ASSASSINO DE PESSOA DESARMADA E INDEFESA?\nE QUE OS SEUS BENS SEJAM ESPOLIADOS PARA RESSARCIR AOS FAMILIARES DA VÍTIMA?"),
    (16, "VOCÊ É A FAVOR DA “PENA DE MORTE” PARA BANDIDOS QUE EXPLODEM CAIXA MULTIBANCO? CRIME CONTRA O POVO (TERRORISMO).\nEM MUITAS CIDADES DO INTERIOR PARA SACAR DINHEIRO, IDOSOS VIAJAM 80 A 100 KMS POR CAUSA DESSE CRIME."),
    (17, "VOCÊ É A FAVOR DA “PENA DE MORTE” PARA BANDIDOS QUE EM ASSALTO EXPLODEM AS CAIXAS MULTIBANCO E USAM REFÉNS COMO ESCUDO HUMANO?\nDESRESPEITO À VIDA ALHEIA, CRIME CONTRA O POVO (TERRORISMO)."),
    (18, "VOCÊ É A FAVOR DA “LEI GANDHI” QUE PROPÕE QUE O CRIME DE HOMICÍDIO SEJA IMPRESCRITÍVEL, INAFIANÇÁVEL E COM CUMPRIMENTO INTEGRAL DA PENA?\nO HOMICÍDIO PRESCREVE EM 20 ANOS (ART. 21 DO CÓDIGO PENAL), MAS O MORTO PERMANECE MORTO."),
    (19, "VOCÊ É A FAVOR DA “PENA DE MORTE” PARA FUNCIONÁRIO QUE DESVIA E (NÃO PULVERIZA) 500 LITROS DA SUBSTÂNCIA QUÍMICA PARA MATAR O MOSQUITO DA ZICA/DENGUE NA CIDADE? CRIME CONTRA O POVO (GENOCÍDIO).\nESTA PERGUNTA É UM TESTE À SUA CONSCIÊNCIA, RESPONSABILIDADE E PRA VER SE VOCÊ É CONSEQUÊNTE."),
    (20, "VOCÊ É A FAVOR DA “PENA DE MORTE” PARA POLÍTICO, FUNCIONÁRIO PÚBLICO OU POLICIAL CORRUPTO ATIVO OU PASSIVO QUE SUBORNA OU DEIXA-SE SUBORNAR?\nO CÂNCER DO BRASIL É A CORRUPÇÃO, PRECISAMOS EXTIRPÁ-LA. CERCA DE 300 BILHÕES POR ANO SÃO DESVIADOS ATRAVÉS DA CORRUPÇÃO."),
    (21, "VOCÊ É A FAVOR DA “PENA DE MORTE” PARA O GARIMPO ILEGAL COM USO DE MERCÚRIO E SUBSTÂNCIAS TÓXICAS PROIBIDAS? CRIME CONTRA O POVO (GENOCÍDIO).\nMUITOS ÍNDIOS NASCEM TETRAPLÉGICOS POR AÇÃO DO MERCÚRIO.\nEM MUITAS CIDADES DO AMAZONAS OS PEIXES ESTÃO IMPRÓPRIOS PARA O CONSUMO POR CAUSA DISSO."),
    (22, "CONCORDAS COM A “LEI GANDHI” DE PROTEÇÃO À VIDA E À INTEGRIDADE FÍSICA (“LEI DA IGUALITARIEDADE DE DIREITOS”, “LEI DA JUSTA RECOMPENSA”):\nSE ALGUÉM AGRIDE OUTRO/A FERINDO, MUTILANDO, INCENDIANDO, CAUSANDO MALES E DEFORMAÇÕES FÍSICAS, SEJA-LHE FEITO O MESMO, NA MESMA PROPORÇÃO, MAIS A PENA DE PRISÃO PREVISTA NA LEI E A ESPOLIAÇÃO DOS SEUS BENS PARA INDENIZAÇÃO FINANCEIRA À VÍTIMA?"),
    (23, "CASO VOCÊ TENHA DISCORDADO DA “PENA DE MORTE EM CARÁTER EFETIVO” PARA ASSASSINOS E PARA POLÍTICOS QUE DESVIAM DINHEIRO PÚBLICO; ENTÃO VOCÊ SERIA A FAVOR DA “LEI DA PENA DE MORTE EM CARÁTER EXPERIMENTAL” POR APENAS 4 ANOS E, CASO DIMINUA SIGNIFICATIVAMENTE (50%) OS REFERIDOS CRIMES, A LEI TORNA-SE PERMANENTE?"),
    (24, "VOCÊ É A FAVOR DA “PENA DE MORTE” PARA FALSIFICADORES E TRAFICANTES DE MEDICAMENTOS FALSIFICADOS?\nSEGUNDO A OMS 10% DOS MEDICAMENTOS NO MUNDO SÃO FALSIFICADOS."),
    (25, "VOCÊ É A FAVOR DA “PENA DE MORTE” PARA TRAFICANTES DE DROGAS PESADAS (COCAÍNA, CRACK, HEROÍNA, LSD, MORFINA, ETC)?"),
    (26, "VOCÊ É A FAVOR DA “SUSPENSÃO IMEDIATA DA IMUNIDADE DIPLOMÁTICA OU IMUNIDADE PARLAMENTAR DOS POLÍTICOS” PARA FINS JURÍDICO OU PENAL QUANDO SÃO SUSPEITOS DE CRIME, PARA QUE SEJAM INVESTIGADOS E JULGADOS AINDA NO EXERCÍCIO PARLAMENTAR?\n(Argumento do texto: a imunidade fere o Art. 5º da Constituição.)"),
    (27, "VOCÊ É A FAVOR DA “PENA DE MORTE” PARA INCENDIÁRIO FLORESTAL CRIMINOSO, DESMATAMENTO ILEGAL E TRÁFICO DE MADEIRA DE ÁRVORES EM VIA DE EXTINÇÃO?\nMUNDIALMENTE, A FUMAÇA DE INCÊNDIOS PROVOCOU 154 MIL MORTES EM 2024 E OUTROS MILHARES SÃO INTERNADOS (PREJUÍZO AOS COFRES PÚBLICOS)."),
    (28, "VOCÊ É A FAVOR DA “LEI GANDHI ANTI-ATROPELAMENTO”: motorista embriagado que atropela alguém ter seus bens espoliados para indenizar a vítima, mais a pena de prisão descrita na lei e cumprimento integral da pena (crime inafiançável)?"),
    (29, "VOCÊ É A FAVOR DA “LEI GANDHI ANTI-FUGA DE MENORES INFRATORES” da instituição onde cumpre medida socioeducativa, e caso haja fuga o menor assume a maior idade penal, cumprindo o restante do tempo em uma prisão para menores?"),
    (30, "VOCÊ É A FAVOR QUE O ESTADO BRASILEIRO FORNEÇA AO JÁ DEPENDENTE QUÍMICO A DROGA NECESSÁRIA PARA O SEU CONSUMO SEMANAL?\nE posteriormente substituir por outra que cause menos dependência e ajude na cura, visando diminuir assaltos e mortes?"),
    (31, "VOCÊ É A FAVOR DA “PENA DE MORTE PARA HACKERS” que danificam sites públicos (Ministério da Saúde, SUS, hospitais etc.) causando mortes e prejudicando a saúde de milhares? (GENOCÍDIO / TERRORISMO CIBERNÉTICO, segundo o texto)"),
    (32, "VOCÊ É A FAVOR DA “LEI GANDHI” para criação oficial da FFGF (Força Federal Guardiões da Floresta), composta por indígenas treinados, armados e incorporados à Polícia Federal?"),
    (33, "VOCÊ É A FAVOR DA “PENA DE MORTE” para bandidos portando (exibindo) armas de guerra como metralhadora, fuzil, granada, dinamite, nitroglicerina em via pública?"),
    (34, "VOCÊ É A FAVOR DA “LEI GANDHI ANTI-FUNCIONÁRIO FANTASMA”: parlamentar em fim de mandato entregar lista de funcionários/assessores para exoneração, sob pena de prisão e multa; e pena de 15 anos para o funcionário fantasma?"),
    (35, "VOCÊ É A FAVOR DA “LEI GANDHI DA DELAÇÃO PREMIADA” nos moldes: se não cooperar aumenta 50% da pena; se cooperar, cumpre só a pena recebida?\n(Comparação do texto com a delação atual.)"),
    (36, "VOCÊ É A FAVOR DA “LEI GANDHI PACIENTE FELIZ” que pune médicos que faltam ao plantão no SUS para atender particular, e pune colegas cúmplices que abonam as faltas, com pena de 10 anos e multa?"),
    (37, "VOCÊ É A FAVOR DA PENA DE MORTE PARA VIOLADOR / ESTUPRADOR DE MENORES VULNERÁVEIS?"),
]

def seed_questions():
    db = SessionLocal()
    try:
        inserted = 0
        skipped = 0

        for order_index, text in QUESTIONS:
            # Idempotente: se já existir uma pergunta com o mesmo order_index, pula
            exists = db.execute(
                select(Question).where(Question.order_index == order_index)
            ).scalar_one_or_none()

            if exists:
                skipped += 1
                continue

            db.add(Question(text=text, active=True, order_index=order_index))
            inserted += 1

        db.commit()
        print(f"✅ Seed concluído. Inseridas: {inserted} | Já existiam (pulado): {skipped}")

    finally:
        db.close()


if __name__ == "__main__":
    seed_questions()
